// The 99 Names of Allah (Al-Asma al-Husna), for the single static /asma-ul-husna
// reference page. Fixed, canonical content - same low-fabrication-risk pattern
// as duas.ts/adhkar.ts, cross-checked against multiple published orderings
// before entry (order and spelling vary slightly across compilations; this
// follows the widely-published ordering traced to the Abu Hurayrah narration
// in Jami' at-Tirmidhi). See AsmaUlHusnaPage.tsx for the sourcing note on the
// hadith grading - the core hadith ("Allah has 99 names...") is authentic
// (Sahih al-Bukhari 7392, Sahih Muslim 2677); the specific enumerated list
// attached to it is a well-known but separately-graded addition, and that
// nuance is stated on the page rather than glossed over.
//
// Bengali meanings are direct working translations, not yet reviewed by a
// native speaker — same caution as the rest of the app's bn content.

export interface AsmaEntry {
  id: string;
  number: number;
  arabic: string;
  transliteration: string;
  meaning: { en: string; bn: string };
}

export const ASMA_UL_HUSNA: AsmaEntry[] = [
  {
    id: 'ar-rahman',
    number: 1,
    arabic: 'الرحمن',
    transliteration: 'Ar-Rahman',
    meaning: { en: 'The Most Compassionate', bn: 'পরম দয়ালু' },
  },
  {
    id: 'ar-raheem',
    number: 2,
    arabic: 'الرحيم',
    transliteration: 'Ar-Raheem',
    meaning: { en: 'The Most Merciful', bn: 'পরম করুণাময়' },
  },
  {
    id: 'al-malik',
    number: 3,
    arabic: 'الملك',
    transliteration: 'Al-Malik',
    meaning: { en: 'The King, the Sovereign', bn: 'পরম অধিপতি' },
  },
  {
    id: 'al-quddus',
    number: 4,
    arabic: 'القدوس',
    transliteration: 'Al-Quddus',
    meaning: { en: 'The Most Holy, Utterly Pure', bn: 'পরম পবিত্র' },
  },
  {
    id: 'as-salam',
    number: 5,
    arabic: 'السلام',
    transliteration: 'As-Salam',
    meaning: { en: 'The Source of Peace', bn: 'শান্তির উৎস' },
  },
  {
    id: 'al-mumin',
    number: 6,
    arabic: 'المؤمن',
    transliteration: "Al-Mu'min",
    meaning: { en: 'The Giver of Security', bn: 'নিরাপত্তা দানকারী' },
  },
  {
    id: 'al-muhaymin',
    number: 7,
    arabic: 'المهيمن',
    transliteration: 'Al-Muhaymin',
    meaning: { en: 'The Guardian, the Overseer', bn: 'রক্ষণাবেক্ষণকারী' },
  },
  {
    id: 'al-aziz',
    number: 8,
    arabic: 'العزيز',
    transliteration: "Al-'Aziz",
    meaning: { en: 'The Almighty', bn: 'পরাক্রমশালী' },
  },
  {
    id: 'al-jabbar',
    number: 9,
    arabic: 'الجبار',
    transliteration: 'Al-Jabbar',
    meaning: { en: 'The Compeller, the Restorer', bn: 'প্রবল ক্ষমতাধর' },
  },
  {
    id: 'al-mutakabbir',
    number: 10,
    arabic: 'المتكبر',
    transliteration: 'Al-Mutakabbir',
    meaning: { en: 'The Supreme in Greatness', bn: 'মহিমান্বিত' },
  },
  {
    id: 'al-khaliq',
    number: 11,
    arabic: 'الخالق',
    transliteration: 'Al-Khaliq',
    meaning: { en: 'The Creator', bn: 'স্রষ্টা' },
  },
  {
    id: 'al-bari',
    number: 12,
    arabic: 'البارئ',
    transliteration: "Al-Bari'",
    meaning: { en: 'The Evolver, the Maker', bn: 'নির্মাতা' },
  },
  {
    id: 'al-musawwir',
    number: 13,
    arabic: 'المصور',
    transliteration: 'Al-Musawwir',
    meaning: { en: 'The Fashioner of Forms', bn: 'রূপদানকারী' },
  },
  {
    id: 'al-ghaffar',
    number: 14,
    arabic: 'الغفار',
    transliteration: 'Al-Ghaffar',
    meaning: { en: 'The Ever-Forgiving', bn: 'পরম ক্ষমাশীল' },
  },
  {
    id: 'al-qahhar',
    number: 15,
    arabic: 'القهار',
    transliteration: 'Al-Qahhar',
    meaning: { en: 'The Subduer of All', bn: 'পরাভূতকারী' },
  },
  {
    id: 'al-wahhab',
    number: 16,
    arabic: 'الوهاب',
    transliteration: 'Al-Wahhab',
    meaning: { en: 'The Bestower of Gifts', bn: 'পরম দানশীল' },
  },
  {
    id: 'ar-razzaq',
    number: 17,
    arabic: 'الرزاق',
    transliteration: 'Ar-Razzaq',
    meaning: { en: 'The Provider', bn: 'রিযিকদাতা' },
  },
  {
    id: 'al-fattah',
    number: 18,
    arabic: 'الفتاح',
    transliteration: 'Al-Fattah',
    meaning: { en: 'The Opener, the Judge', bn: 'বিজয়দাতা' },
  },
  {
    id: 'al-alim',
    number: 19,
    arabic: 'العليم',
    transliteration: "Al-'Alim",
    meaning: { en: 'The All-Knowing', bn: 'সর্বজ্ঞ' },
  },
  {
    id: 'al-qabid',
    number: 20,
    arabic: 'القابض',
    transliteration: 'Al-Qabid',
    meaning: { en: 'The Constrictor', bn: 'সংকোচনকারী' },
  },
  {
    id: 'al-basit',
    number: 21,
    arabic: 'الباسط',
    transliteration: 'Al-Basit',
    meaning: { en: 'The Expander', bn: 'প্রসারণকারী' },
  },
  {
    id: 'al-khafid',
    number: 22,
    arabic: 'الخافض',
    transliteration: 'Al-Khafid',
    meaning: { en: 'The Abaser', bn: 'অবনমনকারী' },
  },
  {
    id: 'ar-rafi',
    number: 23,
    arabic: 'الرافع',
    transliteration: "Ar-Rafi'",
    meaning: { en: 'The Exalter', bn: 'উন্নতকারী' },
  },
  {
    id: 'al-muizz',
    number: 24,
    arabic: 'المعز',
    transliteration: "Al-Mu'izz",
    meaning: { en: 'The Honourer', bn: 'সম্মানদাতা' },
  },
  {
    id: 'al-mudhill',
    number: 25,
    arabic: 'المذل',
    transliteration: 'Al-Mudhill',
    meaning: { en: 'The Humiliator', bn: 'অপমানকারী' },
  },
  {
    id: 'as-sami',
    number: 26,
    arabic: 'السميع',
    transliteration: "As-Sami'",
    meaning: { en: 'The All-Hearing', bn: 'সর্বশ্রোতা' },
  },
  {
    id: 'al-basir',
    number: 27,
    arabic: 'البصير',
    transliteration: 'Al-Basir',
    meaning: { en: 'The All-Seeing', bn: 'সর্বদ্রষ্টা' },
  },
  {
    id: 'al-hakam',
    number: 28,
    arabic: 'الحكم',
    transliteration: 'Al-Hakam',
    meaning: { en: 'The Judge', bn: 'বিচারক' },
  },
  {
    id: 'al-adl',
    number: 29,
    arabic: 'العدل',
    transliteration: "Al-'Adl",
    meaning: { en: 'The Utterly Just', bn: 'ন্যায়পরায়ণ' },
  },
  {
    id: 'al-latif',
    number: 30,
    arabic: 'اللطيف',
    transliteration: 'Al-Latif',
    meaning: { en: 'The Subtly Kind', bn: 'সূক্ষ্মদর্শী দয়ালু' },
  },
  {
    id: 'al-khabir',
    number: 31,
    arabic: 'الخبير',
    transliteration: 'Al-Khabir',
    meaning: { en: 'The All-Aware', bn: 'সর্বজ্ঞাত' },
  },
  {
    id: 'al-halim',
    number: 32,
    arabic: 'الحليم',
    transliteration: 'Al-Halim',
    meaning: { en: 'The Forbearing', bn: 'ধৈর্যশীল' },
  },
  {
    id: 'al-azim',
    number: 33,
    arabic: 'العظيم',
    transliteration: "Al-'Azim",
    meaning: { en: 'The Magnificent', bn: 'মহান' },
  },
  {
    id: 'al-ghafur',
    number: 34,
    arabic: 'الغفور',
    transliteration: 'Al-Ghafur',
    meaning: { en: 'The Great Forgiver', bn: 'ক্ষমাশীল' },
  },
  {
    id: 'ash-shakur',
    number: 35,
    arabic: 'الشكور',
    transliteration: 'Ash-Shakur',
    meaning: { en: 'The Most Appreciative', bn: 'কৃতজ্ঞতা গ্রহণকারী' },
  },
  {
    id: 'al-aliyy',
    number: 36,
    arabic: 'العلي',
    transliteration: "Al-'Aliyy",
    meaning: { en: 'The Most High', bn: 'সর্বোচ্চ' },
  },
  {
    id: 'al-kabir',
    number: 37,
    arabic: 'الكبير',
    transliteration: 'Al-Kabir',
    meaning: { en: 'The Most Great', bn: 'মহান' },
  },
  {
    id: 'al-hafiz',
    number: 38,
    arabic: 'الحفيظ',
    transliteration: 'Al-Hafiz',
    meaning: { en: 'The Preserver', bn: 'সংরক্ষণকারী' },
  },
  {
    id: 'al-muqit',
    number: 39,
    arabic: 'المقيت',
    transliteration: 'Al-Muqit',
    meaning: { en: 'The Sustainer, the Nourisher', bn: 'পুষ্টিদাতা' },
  },
  {
    id: 'al-hasib',
    number: 40,
    arabic: 'الحسيب',
    transliteration: 'Al-Hasib',
    meaning: { en: 'The Reckoner', bn: 'হিসাবগ্রহণকারী' },
  },
  {
    id: 'al-jalil',
    number: 41,
    arabic: 'الجليل',
    transliteration: 'Al-Jalil',
    meaning: { en: 'The Majestic', bn: 'মহিমান্বিত' },
  },
  {
    id: 'al-karim',
    number: 42,
    arabic: 'الكريم',
    transliteration: 'Al-Karim',
    meaning: { en: 'The Most Generous', bn: 'পরম দাতা' },
  },
  {
    id: 'ar-raqib',
    number: 43,
    arabic: 'الرقيب',
    transliteration: 'Ar-Raqib',
    meaning: { en: 'The Ever-Watchful', bn: 'পর্যবেক্ষণকারী' },
  },
  {
    id: 'al-mujib',
    number: 44,
    arabic: 'المجيب',
    transliteration: 'Al-Mujib',
    meaning: { en: 'The Responsive', bn: 'সাড়াদানকারী' },
  },
  {
    id: 'al-wasi',
    number: 45,
    arabic: 'الواسع',
    transliteration: "Al-Wasi'",
    meaning: { en: 'The All-Encompassing', bn: 'প্রশস্ত' },
  },
  {
    id: 'al-hakim',
    number: 46,
    arabic: 'الحكيم',
    transliteration: 'Al-Hakim',
    meaning: { en: 'The All-Wise', bn: 'প্রজ্ঞাময়' },
  },
  {
    id: 'al-wadud',
    number: 47,
    arabic: 'الودود',
    transliteration: 'Al-Wadud',
    meaning: { en: 'The Most Loving', bn: 'প্রেমময়' },
  },
  {
    id: 'al-majid',
    number: 48,
    arabic: 'المجيد',
    transliteration: 'Al-Majid',
    meaning: { en: 'The Glorious', bn: 'গৌরবময়' },
  },
  {
    id: 'al-baith',
    number: 49,
    arabic: 'الباعث',
    transliteration: "Al-Ba'ith",
    meaning: { en: 'The Resurrector', bn: 'পুনরুত্থানকারী' },
  },
  {
    id: 'ash-shahid',
    number: 50,
    arabic: 'الشهيد',
    transliteration: 'Ash-Shahid',
    meaning: { en: 'The Witness', bn: 'সাক্ষী' },
  },
  {
    id: 'al-haqq',
    number: 51,
    arabic: 'الحق',
    transliteration: 'Al-Haqq',
    meaning: { en: 'The Absolute Truth', bn: 'পরম সত্য' },
  },
  {
    id: 'al-wakil',
    number: 52,
    arabic: 'الوكيل',
    transliteration: 'Al-Wakil',
    meaning: { en: 'The Trustee, the Advocate', bn: 'বিশ্বস্ত কর্মবিধায়ক' },
  },
  {
    id: 'al-qawiyy',
    number: 53,
    arabic: 'القوي',
    transliteration: 'Al-Qawiyy',
    meaning: { en: 'The All-Strong', bn: 'পরম শক্তিমান' },
  },
  {
    id: 'al-matin',
    number: 54,
    arabic: 'المتين',
    transliteration: 'Al-Matin',
    meaning: { en: 'The Firm, the Steadfast', bn: 'দৃঢ়' },
  },
  {
    id: 'al-waliyy',
    number: 55,
    arabic: 'الولي',
    transliteration: 'Al-Waliyy',
    meaning: { en: 'The Protecting Friend', bn: 'অভিভাবক বন্ধু' },
  },
  {
    id: 'al-hamid',
    number: 56,
    arabic: 'الحميد',
    transliteration: 'Al-Hamid',
    meaning: { en: 'The Praiseworthy', bn: 'প্রশংসিত' },
  },
  {
    id: 'al-muhsi',
    number: 57,
    arabic: 'المحصي',
    transliteration: 'Al-Muhsi',
    meaning: { en: 'The All-Enumerating', bn: 'গণনাকারী' },
  },
  {
    id: 'al-mubdi',
    number: 58,
    arabic: 'المبدئ',
    transliteration: "Al-Mubdi'",
    meaning: { en: 'The Originator', bn: 'প্রবর্তক' },
  },
  {
    id: 'al-muid',
    number: 59,
    arabic: 'المعيد',
    transliteration: "Al-Mu'id",
    meaning: { en: 'The Restorer', bn: 'পুনরাবর্তনকারী' },
  },
  {
    id: 'al-muhyi',
    number: 60,
    arabic: 'المحيي',
    transliteration: 'Al-Muhyi',
    meaning: { en: 'The Giver of Life', bn: 'জীবনদাতা' },
  },
  {
    id: 'al-mumit',
    number: 61,
    arabic: 'المميت',
    transliteration: 'Al-Mumit',
    meaning: { en: 'The Bringer of Death', bn: 'মৃত্যুদাতা' },
  },
  {
    id: 'al-hayy',
    number: 62,
    arabic: 'الحي',
    transliteration: 'Al-Hayy',
    meaning: { en: 'The Ever-Living', bn: 'চিরঞ্জীব' },
  },
  {
    id: 'al-qayyum',
    number: 63,
    arabic: 'القيوم',
    transliteration: 'Al-Qayyum',
    meaning: { en: 'The Self-Subsisting Sustainer', bn: 'চিরস্থায়ী রক্ষক' },
  },
  {
    id: 'al-wajid',
    number: 64,
    arabic: 'الواجد',
    transliteration: 'Al-Wajid',
    meaning: { en: 'The Finder, the Perceiver', bn: 'প্রাপ্তকারী' },
  },
  {
    id: 'al-majid-2',
    number: 65,
    arabic: 'الماجد',
    transliteration: 'Al-Majid',
    meaning: { en: 'The Noble', bn: 'সম্মানিত' },
  },
  {
    id: 'al-wahid',
    number: 66,
    arabic: 'الواحد',
    transliteration: 'Al-Wahid',
    meaning: { en: 'The One, the Unique', bn: 'এক, অদ্বিতীয়' },
  },
  {
    id: 'as-samad',
    number: 67,
    arabic: 'الصمد',
    transliteration: 'As-Samad',
    meaning: { en: 'The Eternal Refuge', bn: 'অমুখাপেক্ষী' },
  },
  {
    id: 'al-qadir',
    number: 68,
    arabic: 'القادر',
    transliteration: 'Al-Qadir',
    meaning: { en: 'The Able', bn: 'সর্বশক্তিমান' },
  },
  {
    id: 'al-muqtadir',
    number: 69,
    arabic: 'المقتدر',
    transliteration: 'Al-Muqtadir',
    meaning: { en: 'The Omnipotent', bn: 'পূর্ণ ক্ষমতাধর' },
  },
  {
    id: 'al-muqaddim',
    number: 70,
    arabic: 'المقدم',
    transliteration: 'Al-Muqaddim',
    meaning: { en: 'The Expediter', bn: 'অগ্রবর্তীকারী' },
  },
  {
    id: 'al-muakhkhir',
    number: 71,
    arabic: 'المؤخر',
    transliteration: "Al-Mu'akhkhir",
    meaning: { en: 'The Delayer', bn: 'পশ্চাদগামীকারী' },
  },
  {
    id: 'al-awwal',
    number: 72,
    arabic: 'الأول',
    transliteration: 'Al-Awwal',
    meaning: { en: 'The First', bn: 'আদি' },
  },
  {
    id: 'al-akhir',
    number: 73,
    arabic: 'الآخر',
    transliteration: 'Al-Akhir',
    meaning: { en: 'The Last', bn: 'অন্ত' },
  },
  {
    id: 'az-zahir',
    number: 74,
    arabic: 'الظاهر',
    transliteration: 'Az-Zahir',
    meaning: { en: 'The Manifest', bn: 'প্রকাশমান' },
  },
  {
    id: 'al-batin',
    number: 75,
    arabic: 'الباطن',
    transliteration: 'Al-Batin',
    meaning: { en: 'The Hidden', bn: 'গুপ্ত' },
  },
  {
    id: 'al-wali',
    number: 76,
    arabic: 'الوالي',
    transliteration: 'Al-Wali',
    meaning: { en: 'The Governing Patron', bn: 'অভিভাবক' },
  },
  {
    id: 'al-mutaali',
    number: 77,
    arabic: 'المتعالي',
    transliteration: "Al-Muta'ali",
    meaning: { en: 'The Most Exalted', bn: 'সর্বোচ্চ মহিমান্বিত' },
  },
  {
    id: 'al-barr',
    number: 78,
    arabic: 'البر',
    transliteration: 'Al-Barr',
    meaning: { en: 'The Source of All Good', bn: 'কল্যাণকারী' },
  },
  {
    id: 'at-tawwab',
    number: 79,
    arabic: 'التواب',
    transliteration: 'At-Tawwab',
    meaning: { en: 'The Acceptor of Repentance', bn: 'তওবা কবুলকারী' },
  },
  {
    id: 'al-muntaqim',
    number: 80,
    arabic: 'المنتقم',
    transliteration: 'Al-Muntaqim',
    meaning: { en: 'The Avenger of Wrong', bn: 'প্রতিশোধ গ্রহণকারী' },
  },
  {
    id: 'al-afuww',
    number: 81,
    arabic: 'العفو',
    transliteration: "Al-'Afuww",
    meaning: { en: 'The Pardoner', bn: 'ক্ষমাকারী' },
  },
  {
    id: 'ar-rauf',
    number: 82,
    arabic: 'الرؤوف',
    transliteration: "Ar-Ra'uf",
    meaning: { en: 'The Most Kind', bn: 'পরম স্নেহশীল' },
  },
  {
    id: 'al-muqsit',
    number: 83,
    arabic: 'المقسط',
    transliteration: 'Al-Muqsit',
    meaning: { en: 'The Just in Fairness', bn: 'ন্যায়বিচারক' },
  },
  {
    id: 'al-jami',
    number: 84,
    arabic: 'الجامع',
    transliteration: "Al-Jami'",
    meaning: { en: 'The Gatherer', bn: 'একত্রকারী' },
  },
  {
    id: 'al-ghaniyy',
    number: 85,
    arabic: 'الغني',
    transliteration: 'Al-Ghaniyy',
    meaning: { en: 'The Self-Sufficient', bn: 'অভাবমুক্ত' },
  },
  {
    id: 'al-mughni',
    number: 86,
    arabic: 'المغني',
    transliteration: 'Al-Mughni',
    meaning: { en: 'The Enricher', bn: 'প্রাচুর্যদাতা' },
  },
  {
    id: 'al-mani',
    number: 87,
    arabic: 'المانع',
    transliteration: "Al-Mani'",
    meaning: { en: 'The Preventer of Harm', bn: 'প্রতিরোধকারী' },
  },
  {
    id: 'ad-darr',
    number: 88,
    arabic: 'الضار',
    transliteration: 'Ad-Darr',
    meaning: { en: 'The Afflicter (within His wisdom)', bn: 'বিপদদাতা (প্রজ্ঞার অধীনে)' },
  },
  {
    id: 'an-nafi',
    number: 89,
    arabic: 'النافع',
    transliteration: "An-Nafi'",
    meaning: { en: 'The Giver of Benefit', bn: 'কল্যাণদাতা' },
  },
  {
    id: 'an-nur',
    number: 90,
    arabic: 'النور',
    transliteration: 'An-Nur',
    meaning: { en: 'The Light', bn: 'আলো' },
  },
  {
    id: 'al-hadi',
    number: 91,
    arabic: 'الهادي',
    transliteration: 'Al-Hadi',
    meaning: { en: 'The Guide', bn: 'পথপ্রদর্শক' },
  },
  {
    id: 'al-badi',
    number: 92,
    arabic: 'البديع',
    transliteration: "Al-Badi'",
    meaning: { en: 'The Incomparable Originator', bn: 'অতুলনীয় উদ্ভাবক' },
  },
  {
    id: 'al-baqi',
    number: 93,
    arabic: 'الباقي',
    transliteration: 'Al-Baqi',
    meaning: { en: 'The Everlasting', bn: 'চিরস্থায়ী' },
  },
  {
    id: 'al-warith',
    number: 94,
    arabic: 'الوارث',
    transliteration: 'Al-Warith',
    meaning: { en: 'The Inheritor of All', bn: 'উত্তরাধিকারী' },
  },
  {
    id: 'ar-rashid',
    number: 95,
    arabic: 'الرشيد',
    transliteration: 'Ar-Rashid',
    meaning: { en: 'The Guide to the Right Way', bn: 'সঠিক পথনির্দেশক' },
  },
  {
    id: 'as-sabur',
    number: 96,
    arabic: 'الصبور',
    transliteration: 'As-Sabur',
    meaning: { en: 'The Most Patient', bn: 'পরম ধৈর্যশীল' },
  },
  {
    id: 'malik-ul-mulk',
    number: 97,
    arabic: 'مالك الملك',
    transliteration: 'Malik-ul-Mulk',
    meaning: { en: 'Owner of All Sovereignty', bn: 'সার্বভৌম অধিপতি' },
  },
  {
    id: 'dhul-jalali-wal-ikram',
    number: 98,
    arabic: 'ذو الجلال والإكرام',
    transliteration: 'Dhul-Jalali wal-Ikram',
    meaning: { en: 'Lord of Majesty and Generosity', bn: 'মহিমা ও সম্মানের অধিকারী' },
  },
  {
    id: 'al-muhsin',
    number: 99,
    arabic: 'المحسن',
    transliteration: 'Al-Muhsin',
    meaning: { en: 'The Doer of Good', bn: 'কল্যাণকারী' },
  },
];
