import { useEffect, useState, useMemo } from 'react';
import { m as motion } from 'framer-motion';
import { useTranslation } from 'react-i18next';
import { useAnalytics } from '../../hooks/useAnalytics.js';
import { useQuranSummary } from '../../hooks/useQuran.js';
import { useSalatAnalytics } from '../../hooks/useSalatLog.js';
import { useFastingSummary } from '../../hooks/useFasting.js';
import { useAiMuhasabah } from '../../hooks/useAi.js';
import { useAuthStore } from '../../store/useAuthStore.js';
import { AiPanel, AiBadge, AiDisclaimer, AiFallbackNote, AiThinking } from './AiFlair.js';
import { getTrackingDay } from '../../utils/trackingDay.js';
import { loadSurahText } from '../../utils/quranData.js';
import {
  weekIdForMuhasabah,
  pickMuhasabahRef,
  type MuhasabahRef,
} from '../../utils/muhasabahCorpus.js';

const CACHE_KEY = 'bustandeen_muhasabah_report';

interface CachedReport {
  weekId: string;
  wentWell: string;
  slipped: string;
  suggestion: string;
}

function readCache(weekId: string): CachedReport | null {
  try {
    const raw = JSON.parse(localStorage.getItem(CACHE_KEY) ?? '{}') as Partial<CachedReport>;
    return raw.weekId === weekId ? (raw as CachedReport) : null;
  } catch {
    return null;
  }
}
function writeCache(entry: CachedReport): void {
  try {
    localStorage.setItem(CACHE_KEY, JSON.stringify(entry));
  } catch {
    /* full */
  }
}

/** Renders the verified reference card — the ONE thing this feature adds
 * beyond the AI recap: a real, static, hand-verified āyah/hadith, never
 * generated by the AI call above it. */
function ReferenceCard({ reference }: { reference: MuhasabahRef }) {
  const { t, i18n } = useTranslation();
  const isBn = i18n.language?.startsWith('bn');
  const [verseText, setVerseText] = useState<string | null>(null);

  useEffect(() => {
    if (reference.type !== 'quran') return;
    let cancelled = false;
    loadSurahText(reference.surah, ['en.sahih', 'bn.bengali'])
      .then((ayat) => {
        if (cancelled) return;
        const slice = ayat.filter(
          (a) => a.numberInSurah >= reference.ayahStart && a.numberInSurah <= reference.ayahEnd
        );
        const idx = isBn ? 1 : 0;
        const text = slice.map((a) => a.translations[idx] ?? a.translations[0] ?? '').join(' ');
        setVerseText(text || null);
      })
      .catch(() => setVerseText(null));
    return () => {
      cancelled = true;
    };
  }, [reference, isBn]);

  if (reference.type === 'hadith') {
    return (
      <div className="rounded-control border border-brand-gold/25 bg-brand-gold/[0.06] p-3 space-y-1.5">
        <p className="text-white/80 text-sm leading-relaxed italic">
          "{isBn ? reference.textBn : reference.textEn}"
        </p>
        <p className="text-brand-gold text-[11px]">
          {reference.source} · {reference.grade}
        </p>
      </div>
    );
  }

  const citation =
    reference.ayahStart === reference.ayahEnd
      ? `${reference.surahName} ${reference.surah}:${reference.ayahStart}`
      : `${reference.surahName} ${reference.surah}:${reference.ayahStart}-${reference.ayahEnd}`;

  return (
    <div className="rounded-control border border-brand-emerald/25 bg-brand-emerald/[0.06] p-3 space-y-1.5">
      {verseText ? (
        <p className="text-white/80 text-sm leading-relaxed italic">"{verseText}"</p>
      ) : (
        <p className="text-white/55 text-xs">{t('muhasabah.loadingVerse', 'Loading verse…')}</p>
      )}
      <p className="text-brand-emerald text-[11px]">{citation}</p>
    </div>
  );
}

export default function MuhasabahReport() {
  const { t } = useTranslation();
  const user = useAuthStore((s) => s.user);
  const aiEnabled = useAuthStore((s) => s.aiEnabled);
  const { data: zikrData } = useAnalytics(7);
  const { data: quranSummary } = useQuranSummary();
  const { data: salatAnalytics } = useSalatAnalytics(7);
  const { data: fastingSummary } = useFastingSummary();
  const muhasabahMut = useAiMuhasabah();

  const [report, setReport] = useState<CachedReport | null>(null);
  const [dismissed, setDismissed] = useState(false);
  // The AI request failed: show the plain, non-AI version (nothing is cached,
  // so the next visit tries the AI again).
  const failed = muhasabahMut.isError;

  const wk = weekIdForMuhasabah();
  const reference = useMemo(() => pickMuhasabahRef(wk), [wk]);

  const weeklyStats = useMemo(() => {
    if (!zikrData && !quranSummary && !salatAnalytics && !fastingSummary) return null;
    return {
      zikrTotal7d:
        zikrData?.chartData?.reduce((a: number, d: { total?: number }) => a + (d.total ?? 0), 0) ??
        0,
      zikrStreak: zikrData?.streak?.currentStreak ?? 0,
      salatStreak: salatAnalytics?.currentStreak ?? 0,
      salatPct: salatAnalytics?.completionRate ?? 0,
      quranStreak: quranSummary?.streak ?? 0,
      quranAyatToday: quranSummary?.todayAyat ?? 0,
      fastingThisMonth: fastingSummary?.stats?.thisMonth ?? 0,
      trackingDay: getTrackingDay(),
    };
  }, [zikrData, quranSummary, salatAnalytics, fastingSummary]);

  useEffect(() => {
    if (!user || !aiEnabled) return;
    const cached = readCache(wk);
    if (cached) {
      setReport(cached);
      return;
    }
    if (!weeklyStats || muhasabahMut.isPending) return;
    muhasabahMut.mutate(weeklyStats, {
      onSuccess: (r) => {
        const entry: CachedReport = {
          weekId: wk,
          wentWell: r.wentWell,
          slipped: r.slipped,
          suggestion: r.suggestion,
        };
        setReport(entry);
        writeCache(entry);
      },
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps -- deps intentionally narrowed; the omitted values are stable or would retrigger this effect unnecessarily
  }, [user, aiEnabled, wk, !!weeklyStats]);

  if (!user || !aiEnabled || dismissed) return null;
  const showFallback = !report && failed && !!weeklyStats;
  if (!report && !muhasabahMut.isPending && !showFallback) return null;

  return (
    <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>
      <AiPanel>
        <div className="p-4">
          <div className="flex items-center justify-between mb-2">
            <AiBadge label={t('muhasabah.badgeLabel', 'Muhāsabah · this week')} />
            <button
              className="text-white/60 hover:text-white text-xs"
              onClick={() => setDismissed(true)}
              aria-label={t('muhasabah.dismiss', 'Dismiss')}
            >
              {t('muhasabah.dismiss', 'Dismiss')}
            </button>
          </div>

          {muhasabahMut.isPending && !report && (
            <AiThinking
              label={t('muhasabah.thinkingLabel', 'Naseeh is reflecting on your week…')}
            />
          )}

          {report && (
            <div className="space-y-2">
              <p className="text-white/80 text-sm leading-relaxed">{report.wentWell}</p>
              <p className="text-white/75 text-sm leading-relaxed">{report.slipped}</p>
              <p className="text-brand-info text-sm italic">{report.suggestion}</p>

              <div className="pt-2">
                <ReferenceCard reference={reference} />
              </div>
            </div>
          )}

          {showFallback && weeklyStats && (
            <div className="space-y-2">
              <p className="text-white/80 text-sm leading-relaxed">
                {t('muhasabah.fallbackZikr', 'This week you counted {{total}} dhikr.', {
                  total: weeklyStats.zikrTotal7d.toLocaleString('en-GB'),
                })}
              </p>
              <p className="text-white/75 text-sm leading-relaxed">
                {t(
                  'muhasabah.fallbackSalat',
                  "You logged {{pct}}% of this week's prayers. Prayer streak: {{salat}} days. Quran streak: {{quran}} days. Fasts this month: {{fasts}}.",
                  {
                    pct: weeklyStats.salatPct,
                    salat: weeklyStats.salatStreak,
                    quran: weeklyStats.quranStreak,
                    fasts: weeklyStats.fastingThisMonth,
                  }
                )}
              </p>
              <p className="text-brand-info text-sm italic">
                {t(
                  'muhasabah.fallbackSuggestion',
                  'Look at these quietly, then pick one small thing to keep steady next week.'
                )}
              </p>
              <div className="pt-2">
                <ReferenceCard reference={reference} />
              </div>
            </div>
          )}

          {showFallback ? <AiFallbackNote feature="summary" /> : <AiDisclaimer feature="summary" />}
        </div>
      </AiPanel>
    </motion.div>
  );
}
